/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.voxella.launcher.gui;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * Main launcher panel.
 *
 * @author Voxella Project
 */
@ParametersAreNonnullByDefault
public class LauncherPanel extends javax.swing.JPanel {

    private final ResourceBundle resourceBundle = ResourceBundle.getBundle("org/exbin/voxella/launcher/gui/resources/LauncherPanel");
    private final List<JComponent> tabs = new ArrayList<>();
    private final List<JPanel> tabWrappers = new ArrayList<>();
    private int activeTab = -1;
    private JComponent statusPanel;

    public LauncherPanel() {
        initComponents();
        init();
    }

    private void init() {
        tabs.add(new JLabel("Games"));
        tabs.add(new JLabel("Browse"));
        tabs.add(new JLabel("News"));
        tabs.add(null);

        for (JComponent tab : tabs) {
            tabWrappers.add(new JPanel(new BorderLayout()));
        }

        tabbedPane.addChangeListener((e) -> {
            if (activeTab >= 0) {
                tabWrappers.get(activeTab).remove(tabs.get(activeTab));
            }
            activeTab = tabbedPane.getSelectedIndex();
            tabWrappers.get(activeTab).add(tabs.get(activeTab));
        });
        tabbedPane.addTab(resourceBundle.getString("gamesTab.title"), null, tabWrappers.get(0), resourceBundle.getString("gamesTab.toolTip"));
        tabbedPane.addTab(resourceBundle.getString("browseTab.title"), null, tabWrappers.get(1), resourceBundle.getString("browseTab.toolTip"));
        tabbedPane.addTab(resourceBundle.getString("newsTab.title"), null, tabWrappers.get(2), resourceBundle.getString("newsTab.toolTip"));
        tabbedPane.addTab(resourceBundle.getString("aboutTab.title"), null, tabWrappers.get(3), resourceBundle.getString("aboutTab.toolTip"));
    }

    public void setAboutComponent(JComponent component) {
        tabs.set(3, component);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusWrapperPanel = new javax.swing.JPanel();
        headerSeparator = new javax.swing.JSeparator();
        tabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        statusWrapperPanel.setLayout(new java.awt.BorderLayout());
        statusWrapperPanel.add(headerSeparator, java.awt.BorderLayout.NORTH);

        add(statusWrapperPanel, java.awt.BorderLayout.PAGE_END);
        add(tabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JPanel statusWrapperPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    public void setStatusPanel(JComponent statusPanel) {
        if (this.statusPanel != null) {
            statusWrapperPanel.remove(this.statusPanel);
        }
        this.statusPanel = statusPanel;
        statusWrapperPanel.add(statusPanel);
        statusWrapperPanel.revalidate();
    }
}
